### PR TITLE
Remove world_depth_view from Geoserver static

### PR DESCRIPTION
**Pull request by pmbohm**
for https://github.com/aodn/backlog/issues/1046

**** Cannot be merged until replacement config in main Geoservers is deployed ****

### CODE REVIEW

**Comment by pmbohm** [comment]
@aodn/development-team-leader  Is this to be left hanging?

**Comment by ccmoloney** [comment]
@pmbohm Has everything else in the iteration been finished?

**Comment by pmbohm** [comment]
This is my pull request do i wont be the person merging, just bubbling it back up

**Comment by lwgordonimos** [comment]
Merging now, as https://github.com/aodn/geoserver-config/pull/629 has been promoted to production

**Pull request merged**
