### PR TITLE
Fix default map simple

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by pmbohm** [comment]
Fixes https://github.com/aodn/aodn-portal/issues/2573

**Comment by pmbohm** [comment]
TODO: deploy the changes?

**Comment by jonescc** [comment]
Looks like geoserver-static uses the deploy branch of this repo - so probably needs a sync to deploy.

**Comment by anguss00** [comment]
Ok, I can do that

**Comment by pmbohm** [comment]
That sounds like a source of confusion. Why cant it use master?

**Comment by jonescc** [comment]
Actually, its uses the production branch - creating the deploy branch on the node.

Can't think of any reason to use a separate branch unless  we were looking to test this content somewhere else prior to production deployment but it doesn't look like we do this.   

Not sure how much work would be involved in changing this though....

**Pull request merged**
